"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { Header } from "@/components/headers/header";
import Footer from "@/components/footer/footer";
import CustomThemeProvider from "@/components/providers/custom-theme-provider";
import { useProfileStore } from "@/hooks/store/profile.store";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const profileStore = useProfileStore();
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        {/* <ThemeProvider> */}
          <CustomThemeProvider>
            <Header />
            <div
              className="px-[10%]"
              style={{
                backgroundColor: profileStore.bodyColor,
                color: profileStore.bodyTextColor,
              }}
            >
              {children}
            </div>
            <Footer />
          </CustomThemeProvider>
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
