import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { Header } from "@/components/headers/header";
import Footer from "@/components/footer/footer";
import { AccessTokenProvider } from "@/app/AccessTokenContext"; // Import AccessTokenProvider

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        {/* Wrap your layout with AccessTokenProvider */}
        <AccessTokenProvider>
          <ThemeProvider>
            <Header />
            <div className="px-[10%]">{children}</div>
            <Footer />
          </ThemeProvider>
        </AccessTokenProvider>
      </body>
    </html>
  );
}
